language: ruby
sudo: required
# Keep Travis from testing `master` branch
branches:
  except:
  - master

rvm:
  - 2.5.1

before_install:
  - rvm install 2.5.1
  - rvm use 2.5.1
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle check || bundle install

# Deployment config
script:
- echo "skipping tests"

deploy:
  provider: script
  script: sh assets/scripts/build.sh
  skip_cleanup: false
  on:
    branch: travisci

env:
  global:
  - secure: BMlAJ6ZwhpQzoho/fMs9/c4e3qlYSOGuQrkgsUuDfsgm51F47U1AJlVw5aVpGs2AAMsvzhC5gKKovzT9ZIjJfWng9PUUmVKwfpDKFx5C+SEgeuJtjV4ZMi9PK5nLC2GDKJqjaUVsnUb/sE0NZB9bkhj0MzmLzdMOWtWvOiOXZrem9WwZimHpcvyc7X4lP3IW4CXHFUDVU/CHcrPZEYbz4YvuuWu57hB1in/iUQrpwvSkW5UrkRuHeS7jQcX1mSdhv1vppC/3A1o6wg68hsCEueovzqRnXNNAJHHJ+06oCHKnWbIAM9GP37lv4bT5yy86grs4PgSe/04xNM3X1O/c+Um5oUCECqe9XVLqPrleUKyyKws2TRKQcqtXirQe54NSvf7dFRir5voGBNDIQGlcCngBfQk9fudZ375SSv3sfRB/SGXgfbZHE8MXxu7EfnnaWVZsD7xYqC0qISkape6o05ruqGk4oH7Zvz80VGSzdWTVZSs54kiXLazC+IVSwKXAKklcFKJQMoB0PlbnXe1E2S3PoHsWLds7f8tVJljo0VSBldGa0esqqiysr1/9CbSix7E1TRd86V+T6hBxrQb6yrgUgTque6tkG3t+zHQGrGjdTsQEVXoJ+jxbrHahUVDv3gejNenvFh2NOxZPbGhCh3kF/kdBWNzaVvvNZoz8jPc=
  - secure: SmGt9xxlyikrAuZnPwofDYL/4CubQqs6WxM6DmnZcyo+GBeeMhekPuNBzhQ2IywOuBzNlpcFJMXoz9kJY+9ilzrcQ6dytdw3ktbA6rkUwiG26AnBNcgSZD155IjAcVSmhEjzrL1ZNbi8nxZCYYHbaECNXgl6SWHRTpK1DXDAJH49JKdarVm2riuazsYWpOUG+tbSVcpYbbMepaQ/RoyS5GstTEKaFP2lm49vjI09bJ93KyoXHTqw2aFyZFoQ3i9FtxNM59A/SJJtQbzT/l3o4Vfxwx0gWXasf9d1TtTDSleDSxxC4v1+FyrB49iyCX7JvTGc8ti9bSoBPbbsSqJ9ri9wo/3u3zkX3LEasFy40L2lQ7W7zhLiyzJYWPbNvauTaQWl43UeyXznmtaUmJjefU9Vp0DpvxCbIkUwVnMFe50DIqQfG1jV7At1ZI+kvBb1blQr7oZ3KeQTb3RBbs0GkmXvjh8PuBNKQdruczF1CG/W7iADKjvtexqIezLak5oREmlb7fFR5UujRtLi/zCmiHInl1VqzZRagySFCFNXRtiAnbTNE3GoE2ZnWZPnSf+ZujGVT0UmgStBnbC4rjXKy2Ec7uBSFH+xM0eLZ0oxAj/Qu1EW1GaY2dxvSEZbKTjmST96zabU7mgvZIWC0ps7DdDdlmqqfaX1nMRCAa4ehDQ=

