# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings:
title: Vishal Neharkar
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: neharkar.vishal@gmail.com
description: A blog about programming.

baseurl: ""                       # the subpath of your site, e.g. /blog
url: https://neharkar.ml          # the base hostname & protocol for your site

# SEO settings
twitter:
  username: cyb3r_fr3ak
author: vishal_neharkar
social:
  name: Vishal Neharkar
  links:
    - https://twitter.com/
    - https://github.com/neharkarvishal
    - https://www.linkedin.com/in/neharkar

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - venv
  - vendor
sass:
  style: compressed

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
