# Welcome to Jekyll!#
# Used to determine if Google Analytics should be tracking
is_production: 1

# Site settings:
title: Vishal Neharkar
timezone: Asia/Kolkata
email: neharkar.vishal@gmail.com
description: A blog about programming, gaming and internet culture.

baseurl: ""                       # the subpath of your site, e.g. /blog
url: https://neharkar.ml          # the base hostname & protocol for your site
logo: /_assets/img/baseED.png
permalink: /blog/:title/
# SEO settings
twitter:
  username: cyb3r_fr3ak
  card: summary
author:
  twitter: cyb3r_fr3ak
social:
  name: Vishal Neharkar
  links:
    - https://twitter.com/cyb3r_fr3ak
    - https://github.com/neharkarvishal
    - https://www.linkedin.com/in/neharkar
    - https://www.facebook.com/Cyb3r.fr3ak/
    - https://www.instagram.com/vishal_neharkar/

# Build settings
markdown: kramdown
markdown_ext:        "markdown,mkdown,mkdn,mkd,md"
# markdown: redcarpet

include:             [".htaccess"]
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - _assets
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - venv
  - vendor
  - .sass-cache

# Where things are
# source:          .
# destination:     ./_site
# collections_dir: .
# plugins_dir:     _plugins
# layouts_dir:     _layouts
# data_dir:        _data
# includes_dir:    _includes

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

# sass:
#   style: compressed
# Picture element presets
picture:
  source: "assets/img"
  output: "assets/processed-img"
  markup: "picture"
  presets:
    team_square:
      attr:
        class: "image--team-square"
        itemprop: "image"
      ppi: [1, 2]
      source_400:
        media: "(min-width: 400px)"
        width: "334"
      source_default:
        width: "254"
    team_individual:
      attr:
        class: "image--team-individual"
        itemprop: "image"
      ppi: [1, 2]
      source_400:
        media: "(min-width: 400px)"
        width: "288"
      source_default:
        width: "200"
    team_post_meta:
      attr:
        class: "image--team-post-meta"
        itemprop: "image"
      ppi: [1, 2]
      source_default:
        width: "288"
    case_study:
      attr:
        class: "image--case-study"
        itemprop: "image"
      ppi: [1, 2]
      source_860:
        media: "(min-width: 860px)"
        width: "560"
      source_640:
        media: "(min-width: 640px)"
        width: "430"
      source_400:
        media: "(min-width: 400px)"
        width: "560"
      source_default:
        width: "400"
    post_featured_image:
      attr:
        class: "image--post-featured-image"
        itemprop: "image"
      ppi: [1, 2]
      source_1120:
        media: "(min-width: 400px)"
        width: "737"
      source_default:
        width: "400"

# Filtering Content
show_drafts:
limit_posts: 0
future:      false
unpublished: false

# Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: "" # does not include hostname
# show_dir_listing: false

liquid:
  error_mode:       warn
  strict_filters:   false
  strict_variables: false

# gems:
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-picture-tag
